//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial_II_ing_pe
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int correlativo { get; set; }
        public Nullable<int> codProd { get; set; }
        public Nullable<int> cant { get; set; }
    
        public producto producto { get; set; }
    }
}
